name = "Collatz"
uuid = "c1129c9a-098f-4fb3-8893-2df905d125b8"
authors = ["Stefan Karpinski <stefan@karpinski.org> and contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
